matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: linux
      services: docker
      language: generic

language: node_js
node_js: "8"

cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install
  - yarn build:prod